- cmd/main.go
Trivial PR about setting acks=all to the producer.
> Set producer acks all

- internal/services/topic.go
Signed-off-by: Paolo Patierno <ppatierno@live.com>
> Fixed bad variable name

- internal/services/consumer.go
- internal/workers/canary_manager.go
This PR fixes #19 
In order to avoid first messages to be "lost" and not received, it starts the consumer first, waits for it to be subscribed to the partitions and then continue with producing messages.
This is done the first time at startup on topic creation or anyway on each reconcile when consumer and producer need to refresh metadata.
> Fixed consumer starting first and be subscribed before producing

- .gitignore
Signed-off-by: Paolo Patierno <ppatierno@live.com>
> Exclude target folder

- internal/config/canary_config.go
> Making topic internal using "__" prefix

- internal/services/topic.go
- internal/workers/canary_manager.go
> Added backoff retry mechanism on expected cluster size not met

- cmd/main.go
- internal/config/canary_config.go
This PR allows enabling the Sarama logger, through an env var, in order to log on stdout.
> Added flag to enable the Sarama logger

- internal/services/consumer.go
- internal/workers/canary_manager.go
After #45 I forgot to remove an unused parameter. This PR addresses that.
> Removed unused Consume parameter

- cmd/main.go
- internal/config/canary_config.go
- internal/services/consumer.go
- internal/services/producer.go
- internal/services/topic.go
- internal/workers/canary_manager.go
This PR fixes #5.
Some proper error handling was already done in previous PR with backoff algorithm and retries in case of errors where it made sense; this PR is mostly about adding errors related metrics.
> Added a bunch of errors related metrics

- internal/services/topic.go
Just a minor change, more towards the Golang way to have one instruction for error checking.
> Minor change to check err nil

- cmd/main.go
- internal/config/canary_config.go
- internal/security/auth.go
> Added support for SASL PLAIN authentication

- test/e2e_runner_test.go
- test/e2e_test.go
- test/service_manager/service_manager.go
- test/test_utilities.go
Using raw strings for regexp to avoid escaping
Removed useless blank lines
Added check errors inline with if condition
> Some refactoring on e2e tests

- README.md
- internal/config/canary_config.go
This PR adds the description of the configuration parameters on the landing page.
> Added description of canary configuration parameters

- README.md
This PR adds information about how to build the application binary and the corresponding Docker image.
> Added building documentation

- internal/services/connection_check.go
- internal/services/consumer.go
- internal/services/producer.go
- internal/util/util.go
This PR just adds an util package hosting just a common code about getting current time in milliseconds for now.
> Added util package

- internal/services/consumer.go
- internal/services/producer.go
- internal/workers/canary_manager.go
Trivial PR with trivial fixes on comments.
> Fixed some typos on comments

- internal/services/consumer.go
This PR fixes #100.
It was a wrong `return` statement being called when while starting consuming, if an error happens, it exited the go routine and the consume was not calling again.
The code has to `continue` on next for cycle (go routine still running) just waiting a delay before retry.
> Fixed consumer be re-started when error on broker connection

- README.md
Adding the release badge on the landing page.
> Added release badge on the landing page

- install/000-ServiceAccount.yaml
- install/010-Service.yaml
- install/020-Deployment.yaml
This PR adds the missing "install" folder on the main branch with the installation files of the latest released version.
> Added install folder with latest released version installation files

- README.md
Added info about getting help, contributing and license on the landing page.
> Added getting help, contributing and license to landing page

- README.md
This trivial PR adds description about available metrics provided by the canary.
> Added metrics description on the landing page

- test/service_manager/service_manager.go
Signed-off-by: David Kornel <kornys@outlook.com>
> Increase timeout for broker wait in e2e tests

- CHANGELOG.md
This trivial PR just updates the CHANGELOG with latest closed issues.
> Updated CHANGELOG with latest closed issues

- install/020-Deployment.yaml
Trivial PR to update the installation file on main branch to 0.2.0 release.
> Update installation file to new 0.2.0 release

- internal/util/util_test.go
Signed-off-by: kwall <kwall@apache.org>
> adding unit test for IsDisconnection

- CHANGELOG.md
- go.mod
- go.sum
This PR fixes #180 by updating Sarama to 1.34.0 release.
> Updated Sarama to 1.34.0

- install/020-Deployment.yaml
Updated the `Deployment` installation file to use the latest 0.3.0 release.
> Updated installation file to new 0.3.0 release

- CHANGELOG.md
This PR updates the CHANGELOG with https://github.com/strimzi/strimzi-canary/pull/191 in 0.4.0 release.
> Update CHANGELOG with issue #190 in 0.4.0

- CHANGELOG.md
Trivial PR updating the CHANGELOG with fix #204
> Updated CHANGELOG with fix #204

- CHANGELOG.md
- README.md
- internal/services/connection_check.go
First part of replacing connection_error_total with connection_total #143
> Add connection_total metric and deprecate connection_error_total
