internal/services/canary_message.go, internal/services/consumer.go, internal/services/producer.go
This trivial PR added the JSOM message schema as defined by the proposal instead of the current fixed "payload".
It doesn't add the proper message index yet that could be different for each partition.
This will be done in future PR.
=> Added JSON message schema

internal/services/topic.go
This PR fixes #16.
As described in the committed code, this happens in the following scenario.
When the replication factor is less than 3 because brokers are not 3 yet (see `replicationFactor := min(brokersNumber, 3)`),
it's not possible to create the new partitions directly with a replication factor higher than the current ones.
So first alter the assignment of current partitions with new replicas (higher replication factor).
It's not needed anymore when brokers are 3 or more because the replication factor (as 3 max) cannot be higher than that.
The PR does what described even checking that there is no ongoing reassignment ongoing before doing the new partition creation.
=> Fix replica assignment invalid

internal/services/consumer.go
This PR fixes #21 
It introduces waiting with timeout for the consumer to start properly joining the consumer group before starting the producer for sending.
When timed out, it increases a corresponding metric counter; then it retries again after a delay.
=> Added waiting with timeout for consumer to join group

internal/services/backoff.go, internal/services/backoff_test.go, internal/services/consumer.go
This PR fixes #23 
It adds a backoff mechanism for the consumer to delay and retry on joining a consumer group when it times out.
=> Added backoff for consumer retrying to join consumer group

internal/config/canary_config.go, internal/workers/canary_manager.go
This PR removes the old and unused delay for producer and refactor the reconcile interval used now for timing the reconcile on topic and sending messages.
=> Refactoring reconcile interval configuration parameter

internal/config/canary_config.go, internal/services/topic.go
This PR fixes #28 allowing to specify the expected number of brokers on the cluster, creating the topic and assigning partitions accordingly but not handling a dynamic reassignment in case of scale up/down. In this case, the canary has to be restarted and configured with the new expected number of brokers after the scale up/down.
=> Adds configuration of expected brokers to avoid dynamic reassignment

internal/services/backoff.go, internal/services/backoff_test.go, internal/services/consumer.go
The current backoff stuff relying on a misleading meaning of the delay in milliseconds.
This PR reverts everything into Duration terms which defines times in nanoseconds as expected by sleep functions as well.
=> Fixed the backoff with the nanoseconds Duration meaning

cmd/main.go, internal/config/canary_config.go
This PR fixes #33 adding a retrying mechanism to connect Kafka cluster during startup to avoid just exiting if the cluster is not available yet.
=> Adding retrying mechanims to connect Kafka cluster on startup

cmd/main.go, internal/servers/http_server.go, internal/services/healthcheck.go
This PR fixes #27 adding healthcheck endpoints.
Nothing "complex" is done to verify the liveness and readiness of the canary, just returning "OK" for now if the HTTP server is reachable.
=> Added liveness and readiness HTTP endpoints

cmd/main.go, internal/config/canary_config.go
This PR fixes #12 making the Kafka version to use in the Sarama client configurable.
=> Making Kafka version configurable

Makefile
This PR allows changing the name of the built image via a `DOCKER_REPO` env var in the Makefile. Anyway, the default value is still `canary`.
=> Make Docker repo configurable on build

internal/services/consumer.go, internal/workers/canary_manager.go
After digging into Sarama more this PR:
* changes the way to report back that consumer is ready. It's enough signaling in the `Setup` event and not for each consume claim
* no need to refresh metadata on consumer when assignments change, it adapts automatically
=> Refactoring consumer service readiness

cmd/main.go, go.mod, go.sum, internal/config/canary_config.go, internal/servers/http_server.go, internal/services/consumer.go, internal/services/producer.go, internal/services/topic.go, internal/workers/canary_manager.go
This PR fixes #4 and adds a proper logging framework (glog) for logging purposes with different verbosity log levels.
The main change is that all the log messages related to messages produced and consumed with corresponding latency are moved to a kind of verbosity level 1 (DEBUG) while all others are at 0 (INFO).
Notice that compared to how Java log4j framework works, the verbosity level here are like INFO, DEBUG and TRACE that in this specific case are mapped as 0,1 and 2.
=> Added glog library for proper logging

internal/services/topic.go
This PR fixes #44.
In the end it was happening because the Metadata request doesn't return the brokers information in the ascending order of ID (i.e. returning 0,2,1 and not 0,1,2) so the current reassign algorithm was doing a bad assumption on that ordering.
=> Fixed wrong reassignment due to bad brokers order

internal/services/producer.go, internal/services/topic.go, internal/workers/canary_manager.go
This PR fixes #50.
With dynamic reassignment, the producer was sending to less partitions with brokers scaling down not reflecting what's the clients experience (all partitions still reachable even when a brokers goes down).
=> Fixed producer sending to less partitions when less brokers

cmd/main.go, internal/config/canary_config.go, internal/security/security.go
This PR fixes #9 
It allows to specify the TLS CA certificate, client and key directly in the corresponding env vars or using them to specify a path that could be mounted as a Secret (as it could be done by the Strimzi operator in the future and as it's already done for other components).
The code just configures the Sarama library with the corresponding TLS configuration.
=> Added TLS connection support

cmd/main.go
This PR removes a useless select on a channel because it's meant just to block waiting for interrupt signal and nothing more to select.
=> Removed useless select on signal

cmd/main.go
This PR fixes the warning from the go-staticcheck:
`syscall.SIGKILL cannot be trapped (did you mean syscall.SIGTERM?) (SA1016)go-staticcheck`
And anyway it's reported by the signal Go package documentation here https://golang.org/pkg/os/signal/ that SIGKILL cannot be caught.
=> Fixing catch of SIGTERM instead of SIGKILL

internal/services/consumer.go
Before closing the client, it's needed to cancel the context related to the consumer group and exiting the consume loop otherwise while closing, the Sarama library still tries to consume in the loop printing more lines like this:
```shell
I0523 16:45:41.631409   73771 consumer.go:171] Consumer group cleanup
I0523 16:45:41.631481   73771 consumer.go:97] Consumer group consume starting...
I0523 16:45:41.631495   73771 consumer.go:97] Consumer group consume starting...
I0523 16:45:41.631507   73771 consumer.go:97] Consumer group consume starting...
I0523 16:45:41.631518   73771 consumer.go:97] Consumer group consume starting...
I0523 16:45:41.631527   73771 consumer.go:97] Consumer group consume starting...
I0523 16:45:41.631538   73771 consumer.go:97] Consumer group consume starting... …
```
=> Exiting consume loop before closing the client

internal/security/security_test.go
This PR just adds a first unit test for security module when the TLS configuration is created without providing certs but using the system ones.
Other PRs will follow with provided certs.
=> Added system certs unit test

README.md
This trivial PR describes in a better way what happens when the TLS CA certificate configuration parameter is left empty and when it's specified instead.
=> Fixed doc about TLS CA certificate

cmd/main.go, internal/config/canary_config.go, internal/config/canary_config_test.go, internal/services/connection_check.go, internal/workers/canary_manager.go
This PR fixes #84.
It adds a new internal service that periodically check connections to the Kafka brokers in the cluster in order to measure latency the reported via corresponding metrics.
=> Added connection check service

internal/services/consumer.go, internal/services/producer.go, internal/services/topic.go
This PR adds status checking in two additional places - after describing the Canary's topic and when consuming from the topic.
Signed-off-by: Michael Edgar <medgar@redhat.com>
=> Additional status checks for Kafka operations

README.md
This adds the documentation about the env var for configuring the connection checker added via https://github.com/strimzi/strimzi-canary/pull/85
=> Added documentation about env vars related to the connection checker

internal/services/connection_check.go
I noticed that a connection error in the connection checker was printed only at verbosity DEBUG level enabled while as an error it would be important to be there anyway.
=> Logging connection error out of the DEBUG verbosity level

internal/services/connection_check.go
The connection latency metric is about succeeded and failed connections so it's name has to be a generic `connection_latency` (not `connection_success_latency`) even because a tag is used to discriminate success or not.
=> Fixed metric name for canary connection latency

README.md, cmd/main.go, internal/config/canary_config.go, internal/config/canary_config_test.go
This PR fixes #95 using the bootstrap servers parameter as a comma separated list of servers.
=> Fixed bootstrap servers usage as comma separated list of servers

internal/config/canary_config.go, internal/config/canary_config_test.go
This trivial PR enforces the ";" as separator in the topic configuration parameter because with the current regex, any other special character (i.e. ? or $ or % ...) could be used as separator and being accepted.
=> Strict validation of the topic configuration parameter

cmd/main.go, internal/services/connection_check.go, internal/services/topic.go, internal/workers/canary_manager.go
This PR fixes #94 and #98 closing and recreating the Sarama admin client when an EOF error happens (i.e. Kafka rolling, re-authentication timeout, ...) due to Sarama issue not able to reconnect on its own in this use case.
=> Added Sarama admin client recreation on EOF connection error

internal/services/consumer.go
Trivial PR to use the right error log level on consume function error.
=> Fixed log level on consume error

README.md
Adding on the doc that `PLAIN` is the only SASL mechanism supported right now.
=> Added supported SASL mechanisms in the doc

tools/README.md, tools/canary_latencies.py
This script gathers the latency values from the canary logs and calculates the average producer/consumer/connection latencies. This may be useful to determine if the histogram buckets for metrics are set optimally.
It takes input from one or more files and also accepts input (as lines) from STDIN. 
It also sorts the information into quantiles. When calculating quantiles, the quantile method and number of cuts are both configurable. If left unspecified, it will use the defaults for these. 
For reference: 
https://docs.python.org/3/library/statistics.html#statistics.quantiles
=> Add script to calculate canary log latencies and quantiles

README.md, go.mod, go.sum, internal/security/auth.go, internal/security/scram_client.go
This PR fixes #130 
This PR adds support for SASL SCRAM-SHA 256 and 512 mechanisms.
It uses the scram client inspired by the example in the Sarama library [1].
[1] https://github.com/Shopify/sarama/issues/2055
=> Added support for SASL SCRAM-SHA 256 and 512 authentication

internal/services/status_check.go
This PR fixes #144 returning the correct "application/json" content type on the `/status` endpoint.
=> Fixed wrong Content-Type on the status endpoint

internal/services/connection_check.go
This PR fixes #141.
The problem was that the connection service just asked for the cluster topology once and maybe when a Kafka cluster is starting up not all the brokers are ready.
For this reason, the change is about the connection service to refresh the describe cluster until the "expected" number of brokers is reached. This way at the beginning it just tests the already running brokers but at some point it will start testing the last starting ones; from this point in time the topology is not refreshed anymore and if brokers go out and in, it will just checks failed connections increasing the metrics.
Different with dynamic scaling up and down, it will test only the running brokers (part of the topology) so refreshing the topology every time (this behaviour doesn't change from current …
=> Refresh describe brokers when not the expected numbers in connection

.azure/build-pipeline.yaml, test/service_manager/service_manager.go
---
Τhis PR adds the logging into e2e tests with the verbose flag (`-v`). Moreover, it adds logging to the executor commands (i.e., compose actions).
=> Test e2e logs update

CHANGELOG.md
Trivial PR to update the CHANGELOG with info about the Prometheus support via `PodMonitor` and the sample of Grafana dashboard for metrics.
=> Updated CHANGELOG with Prometheus and Grafana examples

CHANGELOG.md, internal/util/util.go
Proposed fix to #159.
Signed-off-by: kwall <kwall@apache.org>
=> Treat ETIMEDOUT (TCP keep-alive failure) as a disconnection conditio too

internal/util/util.go, internal/util/util_test.go
In the end I decided it was best to treat `os.ErrDeadlineExceeded` (i/o timeout) as a disconnected condition.  I was influenced by sarama's own error handling  [consumer.go:818
](https://github.com/Shopify/sarama/blob/712b6bb89287b4767557cc4bf9883148b4979a85/consumer.go#L806) actually closes the broker on any net conditions (`err != nil`).  Having the canary handle this net condition in the same way seemed least worst.  I took the cautious approach and just added `os.ErrDeadlineExceeded` to the existing list of conditions.
=> treat os.ErrDeadlineExceeded (i/o timeout) as a disconnected condition too

cmd/main.go, internal/config/dynamic_config_watcher.go
I didn't notice yesterday that I'd introduced a data-race (reported by `go test --race ./...`) in #166.  Sorry about that.
This first change addresses that.   One of the data races was caused by the use of a value receiver for the #Close() function., which I found really subtle (http://tleyden.github.io/blog/2016/05/19/go-race-detector-gotcha-with-value-receivers/ helped me understand).
The second change addresses thread-safety concerns around the manipulation of sarama.Logger from different go routines without being protected by mutex.  This wasn't reported by `go test --race`.  However I think my proposed change is much easier to reason about in terms of correctness.
The final change ensures that the goroutine beneath the watcher actually ends, rather than being left around.
=> Fix data race issue introduced by #166

internal/services/topic.go
This PR fixed #173 by forcing the canary topic to have `cleanup.policy=delete`.
=> Forced cleanup.policy to delete for the canary topic

CHANGELOG.md, README.md, internal/config/canary_config.go
Trivial PR to update the default Kafka version used by Sarama library to the latest supported 3.1.0
=> Updated default Kafka version used by Sarama to 3.1.0

cmd/main.go
While testing RC2, we found that the end to end latency on the canary was increased.
After some investigation (thanks to @k-wall) it turned out that the following change in Sarama is the root cause: https://github.com/Shopify/sarama/pull/2227
It highlights that there could be a potential bug elsewhere in Sarama which has to be addressed.
Meanwhile, the canary can be updated by setting that consumer max time to the same 250 ms (as before in Sarama).
=> Fixed consumer fetch max wait time due to Sarama potential bug

README.md
Trivial PR to clarify the `Percentage` when there are not enough messages produced/consumed over the time window.
=> Added clarification on not enough samples in status time window

internal/services/topic.go, internal/services/topic_test.go
Proposed fix for #190 .
The change works by, in the case where all brokers are all assigned a rack, it orders the brokers used by the `requestedassignment` function in what KIP-36 calls a [rack alternated broker list.](https://cwiki.apache.org/confluence/display/KAFKA/KIP-36+Rack+aware+replica+assignment#:~:text=The%20rack%20alternated%20list%20will%20be). This list is used by the existing algorithm to create the partition assignments.  If not all brokers have rack information, there's no change to existing behaviour.
This will be applied to both initial assignment and any subsequent reassignment.  If broker pods move between racks for any reason, then the existing partitions will be subject to re-assignment by the existing [alterAssignments](https://github.com/strimzi/strimzi-canary/blob/ …
=> fix: have requestedassignment respect rack

cmd/main.go
Sarama debug logging is made more useful by including the milliseconds portion in the timestamps. With this change the output looks like:
```
[Sarama] 2022/06/08 19:13:47.953676 client/brokers registered new broker #0 at broker-0-penguin-cagbmplvo-vi--h--aog.kas.kwall-kafka.3zz3.s1.devshift.org:443
[Sarama] 2022/06/08 19:13:47.953693 Successfully initialized new client
```
=> include milliseconds is sarama debug log timestamp

CHANGELOG.md, cmd/main.go
Sharing a client meant that the client's await for FetchResponse could skew the latency measurement.  This change means that the producer and consumer services create their own clients.  This will increase the number of connections consumed by the canary on the kafka cluster (by 33%).
Signed-off-by: Keith Wall <kwall@apache.org>
=> fix: #188 use separate sarama clients for producer and consumer

CHANGELOG.md, README.md, internal/config/canary_config.go
following #188, the default producer/end-to-end histogram buckets used by
ihe canary are no longer ideal with all of the obseverations falling into
the <=100ms bucket.  This change introduces smaller buckets and drops the
largest ones.
Signed-off-by: kwall <kwall@apache.org>
=> fix: adjust default producer/end-to-end latency buckets.

CHANGELOG.md
This trivial PR adds the latest OpenTelemetry addition (#197) to the CHANGELOG.
=> Updated CHANGELOG with OpenTelemetry support

install/020-Deployment.yaml, packaging/install/020-Deployment.yaml
containerport was missing in the deployment. This prevented prometheus from scraping the port correctly.
=> fixed missing containerport in deployment

packaging/install/020-Deployment.yaml
This PR removes duplicated `ports` from packaging deployment examples.
=> Remove duplicated ports from packaging deployment files

go.mod, go.sum, internal/config/canary_config_test.go, internal/security/auth_test.go, internal/security/security_test.go, internal/servers/http_server.go, internal/services/backoff_test.go, internal/services/canary_message_test.go, internal/services/connection_check.go, internal/services/consumer.go, internal/services/producer.go, internal/services/status_check.go, internal/services/topic.go, internal/services/topic_test.go, internal/workers/canary_manager.go, internal/workers/canary_manager_test.go, test/e2e_test.go
I want to use mocks in #206 to help write tests to support the bug fix.  To use mocks I require the services to have  interfaces. I've introduced these using a mechanical refactorings.   To keep the reviews easy, I kept this as a separate change.
This change has no functional effect.
=> Refactoring allow for the writing of a canary_manager unit test

README.md, internal/services/consumer.go, internal/services/producer.go, internal/services/topic.go, internal/workers/canary_manager.go, internal/workers/canary_manager_test.go
This minimises the time the canary spends consuming from followers after the partition leadership changes on the cluster. This avoid the end to end latency measure being skewed by the additional latency introduced by the highwatermark propagation between leader/followers.  I left a fuller explanation on this comment: https://github.com/strimzi/strimzi-canary/issues/204#issuecomment-1326695982
=> Fix #204: Have the consuming client refresh its metadata if the partition leadership changes.

Dockerfile
Update Dockerfile with the following OCI label `org.opencontainers.image.source` in the docker image to indicate the source repo URL. This would allow to tools like Renovate to update to point to source and add the release notes when updating the strimzi-canary dependency.
Signed-off-by: Fares Oueslati <oueslati.fares@gmail.com>
=> Add OCI label org.opencontainers.image.source

Makefile.docker, development-docs/DEVELOPING.md
This PR make the docker binary configurable in the Makefile.docker so that `podman` can be used instead. The default is set to `docker` so no changes are needed to continue using the current behaviour.
=> Make the docker binary configurable so that podman can be used

README.md, cmd/main.go, internal/config/canary_config.go, internal/config/canary_config_test.go, internal/services/connection_check.go, internal/services/consumer.go, internal/services/producer.go, internal/services/topic.go, internal/services/topic_test.go, internal/workers/canary_manager.go, internal/workers/worker.go, test/e2e_test.go
This PR adds the option to set constant labels to all Prometheus metrics produced by the canary. These are defined via a semi-colon separated list of key=value pairs, passed in as an enVar.
This PR also includes an attempt to make some of the e2e tests less flaky.
=> Add option to set constant labels for all Prometheus metrics

CHANGELOG.md, internal/services/connection_check.go, internal/services/consumer.go, internal/services/producer.go, internal/services/topic.go, internal/workers/canary_manager.go
Issue: https://github.com/strimzi/strimzi-canary/issues/215
All error-related count metrics except "client_creation_error_total" are initialized with value of 0 to prevent PromQL recognizing first exported metric with error to be initial value.
This way, we can define such prometheus alert rule: `increase(strimzi_canary_topic_alter_configuration_error_total[5m]) > 0`
=> error-related count metrics initialized with 0

.azure/templates/steps/setup_go.yaml, CHANGELOG.md, go.mod, go.sum
Go 1.19 is not supported version, so better to keep updated.
I've updated Go and ran the new code on my setup for around 20 hours.
It functions, and I see a bit less CPU and similar memory usages (yellow : 0.6.0, green : this PR)
CPU
memory
=> chore: Upgraded go version from 1.19 to 1.22
